### ISSUE TITLE
script doesn't find directories

### ISSUE THREAD

**Issue by hrylx** [newbit1/rootAVD#11]
C:\Users\Name\Downloads\Android\rootAVD>rootAVD.bat ListAllAVDs
FIND: '/I': No such file or directory
FIND: 'DEBUG': No such file or directory
FIND: '/I': No such file or directory
FIND: 'PATCHFSTAB': No such file or directory
FIND: '/I': No such file or directory
FIND: 'GetUSBHPmodZ': No such file or directory
FIND: '/I': No such file or directory
FIND: 'ListAllAVDs': No such file or directory
FIND: '/I': No such file or directory
FIND: 'InstallApps': No such file or directory
rootAVD A Script to root AVD by NewBit XDA

Usage:  rootAVD [DIR/ramdisk.img] [OPTIONS] | [EXTRA_CMDS]
or:     rootAVD [ARGUMENTS]

Arguments:
        ListAllAVDs                     Lists Command Examples for ALL installed AVDs
<...>

Is this normal behaviour? 

I also noticed the SKD Folder links are wrong, at least in the readme. For me with newest Android Studio & Win10  it´s in \AppData\Local\Android\Sdk\system-images\android-29\ **google_apis** \x86 and not in \google_apis_playstore\ .

**Comment by newbit1** [comment]
I can not reproduce your issue.
I am using the same System, Windows 10 and Up to Date Android Studio.
If I call `rootAVD.bat ListAllAVDs`
it shows me
`rootAVD.bat %LOCALAPPDATA%\Android\Sdk\system-images\android-29\google_apis\x86\ramdisk.img`

Which is correct.
In the readme are only the Google Play Apis listed, because those Images can't be rooted via adb.
Unlike the Google Apis Images, they can be rooted via adb.
More can be found here:
[[GUIDE] Build / Mod AVD Kernel Android 10 / 11 rootAVD [Magisk] [USB passthrough Linux] [Google Play Store API]](https://forum.xda-developers.com/t/guide-build-mod-avd-kernel-android-10-11-rootavd-magisk-usb-passthrough-linux-google-play-store-api.4212719/)

AVD Images with Google APIs on the other hand are capable of beeing rooted and writeable out of the box.
Actually, just the overlay paritions can be writeable. To achive this, one must start the AVD with the -writable-system
option. What we already doing all the time.
When the AVD is up, go with the ADB commands one by one:
```
adb root
adb shell avbctl disable-verification
adb disable-verity
adb reboot
adb root
adb remount
adb shell
```
Every command must show a positive result, if you stuck in a bootloop or so afterwards,
one of the two disable commands didn't work. Start over with a Wipe Data.
Once the remount command shows remount succeeded, you are good to go.
