### ISSUE TITLE
and we are NOT in an emulator shell

### ISSUE THREAD

**Issue by muZa11** [newbit1/rootAVD#26]
input: adb devices
output:
```
List of devices attached
emulator-5554   device
```

input: ./rootAVD.sh InstallApps
output: 
```
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] Install all APKs placed in the Apps folder
[*] Trying to install Apps/*
```

and stuck there. did i miss anything?

**Comment by newbit1** [comment]
Perhaps this #10 ?!

**Comment by muZa11** [comment]
thanks
i guess this is #10 
i just explored this thread https://forum.xda-developers.com/t/script-rootavd-root-your-android-studio-virtual-device-emulator-with-magisk-android-12-linux-darwin-macos-win-google-play-store-apis.4218123/post-85675159
that video was a bit misleading.  thanks

**Comment by newbit1** [comment]
Yes, sadly, all the Videos about rootAVD are misleading and starting with the wrong command.
Unfortunately, none of these Video makers ever came to me and asked me about it.

**Comment by Davincible** [comment]
@newbit1 Would be nice if you could make your own quick how to guide with commands to copy in the readme, since currently there is no single source of truth, and I had to trial and error copy commands from various vids / the gif in the readme, and eventually also stumbled upon this issue. It seems like people are are experiencing the same :)

Also, there seems to be no clear explanation of what sub commands are run when you just call `./rootAVD.sh <ramdisk>`, after running this command am I still supposed to run any of the other `./rootAVD.sh <ramdisk>` sub commands?

**Comment by newbit1** [comment]
Hi @Davincible,

yes there is, the readme contains the full help menu, which is also shown when you just run the script.
In that help menu, every argument is explained in detail. Also, at the end of it are examples on all possible commands.
I think I can expect users to be able to copy and paste?

If you want to know what happens inside the script, open it and read it. Every task has its own output on the command screen,
and tells you what happens right now.

The script is mend to be as easy, and the readme as detailed, as possible. The new Gifs are even showing you in detail
as well, what to do. What else can I do to make it more clear? You are welcome to show me how you would expect it.
