### ISSUE TITLE
Magisk Alpha not installing properly

### ISSUE THREAD

**Issue by fvrmatteo** [newbit1/rootAVD#39]
Hi,

it looks like the latest 3 releases of Magisk Alpha (44643ad7, 68874bf5, 555a54ec) are not installing properly on the official Android emulators (API 30/31/32). I only got 25201 to install properly, but then even the "Direct Install" method is failing to update to a newer version.

Even though the logs below show a successful execution, the Alpha application is installed, but the root is not present on the device.

Is it a known issue? What would it be the way to proceed to attempt a fix?

The execution log is the following:
```
./rootAVD.sh ~/Android/Sdk/system-images/android-32/google_apis/x86_64/ramdisk.img        
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed. 223.1 MB/s (11954242 bytes in 0.051s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /home/matteo/Android/Sdk/system-images/android-32/google_apis/x86_64/ramdisk.img: 1 file pushed. 223.0 MB/s (3642849 bytes in 0.016s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed. 259.5 MB/s (7847286 bytes in 0.029s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is x64 only
[-] Device SDK API: 32
[-] First API Level: 31
[-] The AVD runs on Android 12
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is online
[!] Checking available Magisk Versions
[?] Choose a Magisk Version to install and make it local
[s] (s)how all available Magisk Versions
[1] local stable '555a54ec-alpha'(25203) (ENTER)
[2] stable 25.2
[3] canary a468fd94(25205)
[4] alpha 44643ad7-alpha(25205)
4
[-] You choose Magisk alpha Version 44643ad7-alpha(25205)
[*] Deleting local Magisk '555a54ec-alpha'(25203)
[*] Downloading Magisk alpha 44643ad7-alpha(25205)
[!] Downloading Magisk alpha 44643ad7-alpha(25205) complete!
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk 44643ad7-alpha(25205) Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[-] copy all x86_64 files from /data/data/com.android.shell/Magisk/lib/x86_64 to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses lz4_legacy compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[-] Multiple cpio archives detected
[*] Unpacking ramdisk ..
[*] Searching for the real End of the 1st Archive
[-] Dumping from 0 to 1692273 ..
Detected format: [lz4_legacy]
[-] Dumping from 1692273 to 3642830 ..
Detected format: [lz4_legacy]
[*] Repacking ramdisk ..
[-] Test patch status and do restore
[-] Checking ramdisk status
[-] STATUS=0
[-] Stock boot image detected
[-] Patching ramdisk
[*] adding overlay.d/sbin folders to ramdisk
Loading cpio: [ramdisk.cpio]
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Dump cpio: [ramdisk.cpio]
[!] PATCHFSTAB=false
[!] Skipping fstab.ranchu patch with /dev/block/sda
[?] If you want fstab.ranchu patched, Call rootAVD with PATCHFSTAB
[!] AddRCscripts=false
[!] Skip adding *.rc scripts into ramdisk.img/sbin/*.rc
[?] If you want *.rc scripts added into ramdisk.img/sbin/*.rc, Call rootAVD with AddRCscripts
[!] patching the ramdisk with Magisk Init
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
[*] repacking back to ramdisk.img format
[!] Copy Magisk.zip to Magisk.apk
[*] Pull ramdiskpatched4AVD.img into ramdisk.img
[-] /data/data/com.android.shell/Magisk/ramdiskpatched4AVD.img: 1 file pulled. 195.6 MB/s (3643110 bytes in 0.018s)
[*] Pull Magisk.apk into 
[-] /data/data/com.android.shell/Magisk/Magisk.apk: 1 file pulled. 203.9 MB/s (11874417 bytes in 0.056s)
[*] Pull Magisk.zip into .
[-] /data/data/com.android.shell/Magisk/Magisk.zip: 1 file pulled. 202.8 MB/s (11874417 bytes in 0.056s)
[-] Clean up the ADB working space
[-] Install all APKs placed in the Apps folder
[*] Trying to install Apps/Magisk.apk
[*] Performing Streamed Install
[*] Success
[-] Shut-Down & Reboot (Cold Boot Now) the AVD and see if it worked
[-] Root and Su with Magisk for Android Studio AVDs
[-] Trying to shut down the AVD
[!] If the AVD doesn't shut down, try it manually!
[-] Modded by NewBit XDA - Jan. 2021
[!] Huge Credits and big Thanks to topjohnwu, shakalaca, vvb2060 and HuskyDG
```

Thanks

**Comment by newbit1** [comment]
Hi @fvrmatteo,
thank you for that feedback. But it seems I can't help you much with it because it doesn't seem to be a rootAVD issue.
I've checked the Alpha 25205 Version, on a Google Play Api 33 Image and I've notices a few things.
The patched Ramdisk looks fine and the boot logs are even showing that the init is booting the system.
But, the Alpha Apk gets deleted during boot up. If I install it manual, it gets deleted right after I want to start it.
I could only get around this, by enabling the developer mode of the system. But still, after a reboot it gets
deleted as well. And If I start the Apk right away, it shows that the core init is **not** started/active/installed.
In the shell I can even run Magisk and su, but it says it is not active or rather running and I can't claim
root rights. So in short, rootAVD installs this Version correctly, but the system is
stopping the init and the apk during the boot process.

Perhaps some of the [changes](https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@14529ae5d3f39e3e9ac5e873eab5026c07653144/notes.md) @vvb2060 made, caused this misbehaviour on the AVD platform?!

notes.md
```
## Magisk (a468fd94) (25205)

- Fix denylist

## Diffs to v25.2

- [General] Fix minor bug in module files mounting implementation
- [MagiskPolicy] Fix minor bug in command line argument parsing
- [Zygisk] Prevent crashing daemon in error
- [Zygisk] Rewrite zygote code injection with new loader library approach
```

The Magisk Stable Version 25.2 and Canary a468fd94(25205) are working just fine.
The direct install Method won't work on AVDs because of the different Ramdisk wrap around file format
compared to a boot.img from a real device. But there is a way or rather work around which let you try this
direct install method anyway. Go to the awesome written script [MagiskOnEmulator](https://github.com/shakalaca/MagiskOnEmulator) from @shakalaca and
check out its fake boot.img function. It will create a fake boot.img with the stock Ramdisk.img from your AVD,
which you can than select as a file for the direct install method. After this patching, you need to get the patched
ramdisk.img out of this fake boot.img and copy it back into your AVD folder.

Please report back If you are going this way, if it works, it could proof me wrong and the issue lies within the rootAVD script.

Cheers
NewBit

**Comment by newbit1** [comment]
Hey @fvrmatteo,
I've proofed me self wrong. I've created a fake boot.img on my own, and with this patched Ramdisk.img the
Alpha 25205 Version works just fine as well.
<img width="339" alt="Screenshot" src="https://user-images.githubusercontent.com/37043777/200140678-252451d0-0b9a-457d-86a1-09cf104a6c07.png">

So this Is indeed an issue with the rootAVD script. My apologies for your inconveniences.
Not sure what to do about it, perhaps I will implement a fake boot.img function as well.
Since I actually don't know what real cause of this issue is.
Cheers

**Comment by fvrmatteo** [comment]
Hello @newbit1, thanks for information you provided so far and no inconvenience at all!

If you won't do it sooner, I'll try implemeting the fake boot.img patching and will test it myself.

I'll get back with more information as soon as I find some time to do it.

**Comment by newbit1** [comment]
Great! I am already on it and will wrap it up soon.

**Comment by fvrmatteo** [comment]
Hello @newbit1 I have some news too, in order:

1. I tested the new option you implemented and it's working properly, even though it could be fully automated, thanks! :rocket: 
2. I understood what's missing to get the new Magisk Alpha versions to work with the default `rootAVD.sh` patching.

I just sent you a PR https://github.com/newbit1/rootAVD/pull/40 with a dummy patch that copies the missing `stub.apk` file, compresses it with `magiskboot` and adds it to the `ramdisk.img`, let's move the conversation there and make sure it's working as expected.
