### ISSUE TITLE
Feature Request: Environmental Variables file

### ISSUE THREAD

**Issue by dstack4273** [newbit1/rootAVD#73]
Thanks for the neat and handy tool. I found that the batch script (and shell script) have the location of the system-images and platform-tools hardcoded to the default installation directory location. I was able to hack things to where I've got stuff saved off, but for ease of use for others it would be swell to just have an env file to that gets read in with the default directories listed.  If you're bored you can take a look at something like that, or if I get a chance I'll try to throw a PR over after testing and what not.

**Comment by newbit1** [comment]
Hi @dstack4273,

yes this FR is very welcome. In issue #42 was already this topic opened, but never further processed.
I would like to use some of these Environment variables from AOSP to accomplish this.
Instead of creating another file. The hardcoded version comes from the standard directories, but
people with different directories having problems to get it right.

So If you can post me your specific directory structures, I will implement something while using
it as a use case. And you can try it out to verify it. You can also send me a PR and I will take this into
account as well.

**Comment by newbit1** [comment]
Hey @dstack4273,
you can try this feature now, if you are on windows. #74
