### ISSUE TITLE
Zygisk is not working

### ISSUE THREAD

**Issue by darshgopani23** [newbit1/rootAVD#95]
Zygisk is not working for me on my AVD with Android 14. I am trying to install a module that requires zygisk, but it simply does not work.

**Comment by newbit1** [comment]
which magisk version?
How did you installed it?
Which Module?
Did you enable zygisk?

**Comment by fatshotty32** [comment]
The default magisk version 15.2. I tried to install the latest one using the magisk app but it just did not update after the reboot, it stayed on 15.2. I was trying to install Lsposed module (zygisk version) but it did not work. The toggle for zygisk was on after reboot but the module did not work because the homepage of magisk said "Zygisk: No"
